# Generated by Django 4.2.11 on 2024-04-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('resolutionID', models.IntegerField(primary_key=True, serialize=False)),
                ('resolution', models.CharField(max_length=30)),
                ('video_url', models.URLField(max_length=300)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='streamingApp.video')),
            ],
        ),
    ]
