# Generated by Django 4.2.11 on 2024-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingApp', '0002_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
