# Generated by Django 4.2.11 on 2024-04-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingApp', '0004_alter_video_description_alter_video_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='resolution',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolutionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='video_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
